# -*- coding: utf-8 -*-
"""NLP_PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mlrD-DCAn9NgWjHTNBEskDxPbnQf3oli
"""

!pip install rouge-score
!pip install bert-score
!pip install git+https://github.com/keras-team/keras-hub.git py7zr -q
import os
os.environ["KERAS_BACKEND"] = "jax"
import py7zr
import time
import keras_hub
import keras
import tensorflow as tf
import tensorflow_datasets as tfds
BATCH_SIZE = 4
NUM_BATCHES = 600
EPOCHS = 1
MAX_ENCODER_SEQUENCE_LENGTH = 512
MAX_DECODER_SEQUENCE_LENGTH = 128
MAX_GENERATION_LENGTH = 40
filename = keras.utils.get_file(
    "corpus.7z",
    origin="https://huggingface.co/datasets/samsum/resolve/main/data/corpus.7z",
)
with py7zr.SevenZipFile(filename, mode="r") as z:
    z.extractall(path="/root/tensorflow_datasets/downloads/manual")
samsum_ds = tfds.load("samsum", split="train", as_supervised=True)
for dialogue, summary in samsum_ds:
    print(dialogue.numpy())
    print(summary.numpy())
    break
import time
import tensorflow as tf
import tensorflow_datasets as tfds
from transformers import BartTokenizer, BartForConditionalGeneration, pipeline
from rouge_score import rouge_scorer
import torch
import bert_score

def train_bart_model():
    train_ds = tfds.load("samsum", split="train", as_supervised=True)
    BATCH_SIZE = 4
    NUM_BATCHES = 600
    EPOCHS = 1

    train_ds = (
        train_ds.map(
            lambda dialogue, summary: {"encoder_text": dialogue, "decoder_text": summary}
        )
        .batch(BATCH_SIZE)
    )
    train_ds = train_ds.take(NUM_BATCHES)

    tokenizer = BartTokenizer.from_pretrained("facebook/bart-base")
    hf_model = BartForConditionalGeneration.from_pretrained("facebook/bart-base").to("cuda")

    optimizer = torch.optim.AdamW(
        hf_model.parameters(),
        lr=5e-5,
        weight_decay=0.01,
        eps=1e-6,
    )
    accumulation_steps = 4
    scaler = torch.cuda.amp.GradScaler()

    for epoch in range(EPOCHS):
        for i, batch in enumerate(train_ds):
            encoder_input = tokenizer(
                [text.numpy().decode("utf-8") for text in batch['encoder_text']],
                padding=True,
                truncation=True,
                max_length=512,
                return_tensors="pt"
            ).to("cuda")
            decoder_input = tokenizer(
                [text.numpy().decode("utf-8") for text in batch['decoder_text']],
                padding=True,
                truncation=True,
                max_length=512,
                return_tensors="pt"
            ).to("cuda")

            with torch.cuda.amp.autocast():
                outputs = hf_model(input_ids=encoder_input['input_ids'], labels=decoder_input['input_ids'])
                loss = outputs.loss / accumulation_steps
            scaler.scale(loss).backward()

            if (i + 1) % accumulation_steps == 0:
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad()
            torch.cuda.empty_cache()

            print(f"Epoch: {epoch + 1}/{EPOCHS}, Batch: {i + 1}/{NUM_BATCHES}, Loss: {loss.item()}")

    return hf_model, tokenizer
def generate_text_with_beam_search(model, tokenizer, input_text, max_length=200, num_beams=5, print_time_taken=False):
    """Generates text using beam search with Hugging Face Transformers."""
    start = time.time()

    generator = pipeline("summarization", model=model, tokenizer=tokenizer, device=0) # Run on GPU
    outputs = generator(input_text, max_length=max_length, num_beams=num_beams)
    generated_text = [output['summary_text'] for output in outputs]

    end = time.time()
    if print_time_taken:
        print(f"Total Time Elapsed: {end - start:.2f}s")
    return generated_text

def load_validation_dataset():
    val_ds = tfds.load("samsum", split="validation", as_supervised=True)
    val_ds = val_ds.take(100)

    dialogues = []
    ground_truth_summaries = []
    for dialogue, summary in val_ds:
        dialogues.append(dialogue.numpy().decode('utf-8'))
        ground_truth_summaries.append(summary.numpy().decode('utf-8'))

    return dialogues, ground_truth_summaries
def evaluate_summaries(generated_summaries, references):
    rouge_scorer_obj = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
    rouge_scores = [rouge_scorer_obj.score(ref, gen) for ref, gen in zip(references, generated_summaries)]
    P, R, F1 = bert_score.score(generated_summaries, references, lang="en", verbose=True)

    avg_rouge1 = sum([score['rouge1'].fmeasure for score in rouge_scores]) / len(rouge_scores)
    avg_rouge2 = sum([score['rouge2'].fmeasure for score in rouge_scores]) / len(rouge_scores)
    avg_rougeL = sum([score['rougeL'].fmeasure for score in rouge_scores]) / len(rouge_scores)
    avg_bert_f1 = torch.mean(F1).item()

    print(f"Average ROUGE-1: {avg_rouge1:.4f}")
    print(f"Average ROUGE-2: {avg_rouge2:.4f}")
    print(f"Average ROUGE-L: {avg_rougeL:.4f}")
    print(f"Average BERTScore F1: {avg_bert_f1:.4f}")

def main():
    hf_model, tokenizer = train_bart_model()
    dialogues, ground_truth_summaries = load_validation_dataset()
    generated_summaries_beam = generate_text_with_beam_search(
        model=hf_model,
        tokenizer=tokenizer,
        input_text=dialogues,
        max_length=200,
        num_beams=5,
        print_time_taken=True
    )

    evaluate_summaries(generated_summaries_beam, ground_truth_summaries)
    return generated_summaries_beam, ground_truth_summaries

if __name__ == "__main__":
     generated_summaries_beam, ground_truth_summaries = main()
print( generated_summaries_beam[0])
print(ground_truth_summaries[0])

test_conversation = """
John: Hey, are you coming to the meeting tomorrow?
Harry: Yes, I’ll be there. What time does it start?
John: It’s at 10 AM in Conference Room.
Harry: Perfect, thanks for the reminder!
John: No problem, see you there!
"""

reference_summary = "Harry confirmed they will attend the meeting at 10 AM in Conference Room."
hf_model, tokenizer = train_bart_model()
def test_sample(conversation, reference_summary, model, tokenizer):
    generator = pipeline("summarization", model=model, tokenizer=tokenizer)
    generated_summary = generator(conversation, max_length=200, num_beams=5)[0]['summary_text']
    print("Generated Summary:", generated_summary)
    print("Reference Summary:", reference_summary)

    rouge_scorer_obj = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
    rouge_scores = rouge_scorer_obj.score(reference_summary, generated_summary)

    print("\nROUGE Scores:")
    print(f"ROUGE-1: {rouge_scores['rouge1'].fmeasure:.4f}")
    print(f"ROUGE-2: {rouge_scores['rouge2'].fmeasure:.4f}")
    print(f"ROUGE-L: {rouge_scores['rougeL'].fmeasure:.4f}")

    P, R, F1 = bert_score.score([generated_summary], [reference_summary], lang="en", verbose=True)
    avg_bert_f1 = torch.mean(F1).item()

    print("\nBERTScore F1:", avg_bert_f1)
test_sample(test_conversation, reference_summary, hf_model, tokenizer)